### ISSUE TITLE
trident installer fails to set the Time Zone

### ISSUE THREAD

**Issue by mrT55** [project-trident/trident-installer#14]
I installed: Trident-x64-20180831.iso
and during the install prompting, I set the time zone.

After the install completed and the first boot I
discovered the system time zone was not set.

**Comment by RodMyers** [comment]
have you attempted to use RC3?

The TZ option is how you set the BIOS time.

**Comment by beanpole135** [comment]
This appears to be working on 18.12-RELEASE.
