### ISSUE TITLE
Installation Failed Screen - Can't see all text

### ISSUE THREAD

**Issue by jimbygh** [project-trident/trident-installer#16]
If the install fails, the "Installation Failed" screen is shown.  The text on the second line is not readable in vesa mode.  The font is too big and/or the text is too long.

**Comment by jimbygh** [comment]
![installfailed2](https://user-images.githubusercontent.com/42945727/45159297-62865300-b1b4-11e8-8333-c86cba67fc95.png)

**Comment by beanpole135** [comment]
Fixed for BETA3
The text label has been set to automatically wrap around and show multiple lines as needed.
