### ISSUE TITLE
Troubles with localization

### ISSUE THREAD

**Issue by berrandonea** [project-trident/trident-installer#19]
Hello. Thanks for your work on this promising system. I noticed troubles with localization. The installer doesn't let me choose a time zone nor a keyboard layout (I can choose various keyboard brands but no layout). I can choose a language but it has no effect on the installer, which remains in English. Then, I have to choose passwords using a keyboard layout that's not my real one. Once I reboot in the installed system, the language is en_US, although I had chosen fr_FR in the installer.

**Comment by beanpole135** [comment]
A few quick notes:
1. Time Zone: There is a drop-down list on the first page of the installer for setting the time and time zone. This appears to be working fine in testing, as it is only used to "stamp" the installed system with the proper timezone information.
2. Keyboard Layout: I ave also noticed that the keyboard layout options are not always present. I am still investigating, but my hunch is that we need to install some additional xorg packages on the ISO to ensure the keyboard options are all present.
3. Localization: The localization options are in place and functioning, but there have been no translations actually performed yet, resulting in the default (en_US) text getting displayed for all languages at the present time. We are working on a system to allow people to easily perform/submit translations for various utilities and hope to have an announcement about sometime in the near future. In the meantime, you can send in a Pull Request (PR) for the [translation files](https://github.com/project-trident/trident-installer/tree/master/src-qt5/i18n) directly through GitHub if you like (XML files).
4. Transfer of settings to the installed system: Please look at issue #22 for updates on this. We are aware of the issue and are looking into solutions for it now.

Thank you for reporting these issues!

**Comment by berrandonea** [comment]
You're welcome. I just submitted a pull request for the french translation.
Good luck for the release.

**Comment by RodMyers** [comment]
Can you try the RELEASE ISO?

**Comment by RodMyers** [comment]
closed, lack of response
