### ISSUE TITLE
Verify: Install to full disk

### ISSUE THREAD

**Issue by beanpole135** [project-trident/trident-installer#2]
Verify that an install to a full, single disk works properly

* VirtualBox VM is a good test of this

**Comment by miker** [comment]
On my first attempt using Beta1 I selected full, single disk and the install failed. "No partition schemes found" I rebooted the installer and this time the ZFS partitioning was there. I selected the previously created ZFS partitioning and the installer is happy.

Currently installing :)

**Comment by miker** [comment]
VirtualBox install failed. 
EXITERROR: Error 1: 
mount -t msdosfs /dev/ada0p /mnt/boot/efi
Cleaning up...
For more details see log file: /tmp/.pc-sysinstall/pc-sysinstall.log

If I were to hazard a guess, the /boot/efi partition wasn't properly created?

**Comment by RodMyers** [comment]
Was this BIOS or UEFI

**Comment by miker** [comment]
Here is a screenshot from the pc-sysinstall.log 
Really github, no image upload?
VirtualBox using UEFI
https://filebin.pw/AGBhHL/

**Comment by miker** [comment]
Went through the installer again after it failed with the /boot/uefi issue. Here's a pic of the installer's Install Location. It looks like the space for the /boot/uefi partiton is there, just not active or being used?
The screenshot shows Free Space (329MB)
https://filebin.pw/TxG0cZ/

**Comment by revhelix** [comment]
Currently Looking at the stage dated for Sept 5th, Using VMware workstation 14 on Ubuntu.
When installing to disk, the Free Space is able to be selected, but fails.

But upon the next attempt to install, the disk was modified from the previous attempt, but the da0(disk) is then select-able, and able to continue on with the install.

**Comment by RodMyers** [comment]
Beta 2 installed on a Lenovo Carbon X1 2nd gen just fine

**Comment by RodMyers** [comment]
Beta 3 installed on a Lenovo Carbon X1 2nd gen just fine.

could probably close this issue
