### ISSUE TITLE
Problem booting installer from usb[BETA2]

### ISSUE THREAD

**Issue by hpigula** [project-trident/trident-installer#21]
I have problems  booting my usb drive on uefi with this error:

![image](https://user-images.githubusercontent.com/41572588/45549175-c8ab4f80-b81e-11e8-9ee6-3c3e6fd10cf8.png)

on laptop:
Model: Lenovo ideapad 310s-15abr 80st
System: Dual-boot linux(Antergos) and windows 10 on another hdd
HDD1: 2x WD Blue 1TB
CPU: AMD A10 9600p
GPU: Radeon R5 iGPU
RAM: 8 GB DDR4(2x4GB)
USB: USB thumb with USB3.0 16GB
Any solutions??

**Comment by beanpole135** [comment]
Typically this has one of the following causes:
1. Corrupted ISO download. 
   * Verify that the ISO checksum post-download matches the published checksum.
2. Bad Copy/Burn to USB/DVD
   * Many popular image burning tools do not handle FreeBSD image files properly. The best way is to use the "dd" utility on a Linux/BSD system with the following command: `dd if=[path to ISO file] of=/dev/[USB device - make sure this is not a partition on the stick but the whole device!!] bs=5M conv=sync`
3. BIOS Configuration
   * UEFI mode is recommended, but CSM mode for UEFI must be disabled for optimum results.

**Comment by RodMyers** [comment]
have you attempted to use RC3?
