### ISSUE TITLE
Transfer Keyboard/Locale settings to PCDM

### ISSUE THREAD

**Issue by beanpole135** [project-trident/trident-installer#22]
Original Issue: https://github.com/project-trident/trident-build/issues/4

While the keyboard/locale options are getting properly set in the pc-sysinstall config, it does not appear that pc-sysinstall is saving those variables on the installed system properly since PCDM still shows the default locale/keyboard settings on first boot.

Possible Solution:
1. In the installer, assemble a custom config file with various options (locale, keyboard, timezone, possibly other options later) and place it into the installed system at the end of the install process.
2. In trident-core (/usr/local/share/trident/scripts/*) write a parsing script for ensure those config options are enabled properly on the installed system as needed for PCDM or other tools.

**Comment by RodMyers** [comment]
is this fixed with the RELEASE ISO?

**Comment by RodMyers** [comment]
closed lack of response
