### ISSUE TITLE
When installing under VMWare on MacBook Pro buttons are off screen bottom

### ISSUE THREAD

**Issue by zslg01** [project-trident/trident-installer#24]
While installing under VMWare on MacBook Pro - Retina, the buttons you need to click to proceed are off screen at the bottom. Makes it hard to continue.

**Comment by RodMyers** [comment]
have you tried with the RELEASE ISO?

**Comment by AndiDog** [comment]
Same for me using Trident-18.12-RELEASE-x64-20190115.iso

![Screenshot](https://pbs.twimg.com/media/DxgVfIsX4AAgLj-.png)

**Comment by powernap** [comment]
I had this issue as well on VMware Workstation 15, but after talking to Ken, I went into advanced options for the VM and changed from BIOS to UEFI and it fixed the issue.

**Comment by RodMyers** [comment]
> Same for me using Trident-18.12-RELEASE-x64-20190115.iso
> 
> ![Screenshot](https://camo.githubusercontent.com/80493c4488239774af62634801e68fb2741681ef/68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f4478675666497358344141674c6a2d2e706e67)

Can you check that out as well?

**Comment by josemaX** [comment]
Change to UEFI solved this for me in 19.07-20190710.iso

**Comment by beanpole135** [comment]
Closing out this issue due to the move to Void Linux: Completely different backend/installer.

Just for reference though: 
Switching to EFI or UEFI boot within VMWare fixes this issue. It appears to be some kind of mismatch in the VMWare/FreeBSD resolution reporting for legacy-boot.
