### ISSUE TITLE
Option to install to new BE disabled

### ISSUE THREAD

**Issue by barulheira** [project-trident/trident-installer#27]
I have TrueOS installed and running fine (17.12, 18.03), booting UEFI with Linux Mint's GRUB2 bootloader.

The installer finds the ZFS partition, I can select it, but it does not enable the option to install to a new boot environment.

(Edit: actually, no 18.06 here)

**Comment by RodMyers** [comment]
Have you attempted to use RC3?

**Comment by barulheira** [comment]
Yes. The issue is still there. The option button is there. But it cannot be clicked, checked, activated... anyway.

**Comment by barulheira** [comment]
It remains in the current PRERELEASE installer.

**Comment by barulheira** [comment]
It remains in the current RELEASE installer.

I ask you: if that option is really supposed to be disabled when the boot environments were created for TrueOS 18.03 and earlier, then, please, close this issue.

**Comment by beanpole135** [comment]
Detection of available ZFS pools for installing into a boot environment comes from the pc-sysinstall utility from TrueOS itself. If that is not reporting any bootable ZFS pools, then the install to boot environment option gets automatically disabled.
This might be a good thing to raise with the TrueOS team (https://github.com/trueos/trueos), to see if they know of any changes to the BE code which is preventing detection of older ZFS pools.
