### ISSUE TITLE
swap zvol for default single partition installation

### ISSUE THREAD

**Issue by jgroenveld** [project-trident/trident-installer#29]
```
Installer should recommend, create, and add to fstab(5) a swap zvol 
in the case of a single zpool partition configuration without a dedicated swap gpart.
John
groenveld@acm.org
```

**Comment by RodMyers** [comment]
I don't think zfs creates an fstab entry.

**Comment by jgroenveld** [comment]
```
Currently its a manual, post-installation process:
# zfs create -V 8G tank/swap
# echo "/dev/zvol/tank/swap none swap sw 0 0" >>/etc/fstab
# swapon -a

John
groenveld@acm.org
```

**Comment by RodMyers** [comment]
RC3 adds it

cat /etc/fstab 
# Device                Mountpoint              FStype          Options Dump Pass
/dev/label/swap0.eli    none            swap    sw      0       0

**Comment by jgroenveld** [comment]
```
That's a GELI swap partition.
See gpart(8) show
John
groenveld@acm.org
```

**Comment by RodMyers** [comment]
what does

gpart show

show? Have you tried th RELEASE ISO>

**Comment by RodMyers** [comment]
gpart show
=>       40  468862048  ada0  GPT  (224G)
         40     204800     1  efi  (100M)
     204840  466538496     2  freebsd-zfs  (222G)
  466743336    2097152     3  freebsd-swap  (1.0G)
  468840488      21600        - free -  (11M)

works, for me, in the RELEASE ISO
