### ISSUE TITLE
Verify: Install to BE

### ISSUE THREAD

**Issue by beanpole135** [project-trident/trident-installer#3]
Verify that an install into a new Boot Environment works properly.

Good test system
* Previously-installed TrueOS 18.03 "desktop" edition

**Comment by beanpole135** [comment]
Seems to work in VirtualBox with one caveat:
The new BE is not automatically activated - the new BE needs to be activated either via the boot menu or with `beadm` from within the old BE.

**Comment by RodMyers** [comment]
Tested "staged" Trident-x64-20180905.iso  , installed into 18.03 laptop with NO issues, except as mentioned above. Never gets activated. WiFi had to have script run and /etc/rc.conf edited to make saure entry has "SYNCDHCP" instead of "DHCP".

**Comment by beanpole135** [comment]
This has been tested and verified working.
The new boot environment has also setup for automatic activation.
