### ISSUE TITLE
sysctl failed to start

### ISSUE THREAD

**Issue by ZoltanHegedus** [project-trident/trident-installer#30]
Hello!
I got these error messages under the boot process of the installer media (.iso) 

unknown oid "debug.witness.trace"     therefore the sysctl failed to start

other error message:

devd line 29:device:syntax error

And when I have to choose the place for the new system, the field of "Select Installaton Location" this is usually empty:

https://imgur.com/a/CR7fZHu

If I click on the "Previous" and after again on the "Next" then after few try the harddrives will appear and I can continue the install procedure:

https://imgur.com/a/6Fno9UU

Under the verbose boot process  of the installer the HDD and the SSD are visible (manufacturer, type, serial number etc).

My machine is an hybrid graphical Acer Aspire E17 (Intel-Nvidia combo- Nvidia Optimus) and the Beta2 used the vesa driver, this was not the best, but it could to work. 
Now the Beta3 would like to use the Intel driver, but it couldn't not. When the installed system start, I got a black screen with the command prompt, I can login, but if I login the first thing what I get is a "zsh-newuser-install" answer. So far I tried some videodriver variation unsuccessfully. The /etc/X11/xorg.conf is OK, maybe the nvidia or intel_load yes line missing from the /boot/loader.conf, I will check this, now I haven't more idea yet.

**Comment by RodMyers** [comment]
Have you tried the RELEASE ISO?

**Comment by RodMyers** [comment]
are/were you coming from trueos 1803?

this is a known issue with FreeBSD changing the bootloader programming language from forth to lua

please try the RELEASE ISO

**Comment by beanpole135** [comment]
This was fixed quite a long time ago. Closing issue.
