### ISSUE TITLE
Rename or copy /usr/local/etc/devd/cups.conf.sample  on install

### ISSUE THREAD

**Issue by jimbygh** [project-trident/trident-installer#31]
The file /usr/local/etc/devd/cups.conf is used to enable cups to make use of usb printer devices.

With the correct name as /usr/local/etc/devd/cups.conf , devd will read it on startup.

**Comment by beanpole135** [comment]
This should be fixed in RC3+.
We found an error that the `pkg` post-install commands were not getting run properly during the installation and that is where the sample config files are automatically copied over to the "live" locations as needed.
