### ISSUE TITLE
Fresh Installation Failure With Swap Partition 

### ISSUE THREAD

**Issue by maxsteciuk** [project-trident/trident-installer#32]
Multiple attempts to configure fresh full disk installation with Swap partition led the overall installation failure. Several values for Swap partition were tested: 520 MB, 1024 MB, 2055 MB. The log indicates the ZFS import trident showing exit error code 1. 

pc-sysinstall.log log error message:

> cannot import 'trident': invalid  vdev configuration
> 
> EXITERROR: Error 1: zpool -f -N trident

**Comment by RodMyers** [comment]
RC3, clean install on a 2nd Gen X1 carbon. Swap file created just fine

**Comment by maxsteciuk** [comment]
UPDATE:

The following workaround steps worked for : 
1. Clean drive completely as follows:

> dd if=/dev/zero of=/dev/ada1 bs-16M

2. Go to installer 
3. Add swap partition

Bottom line:
Either installer can add this step as a hack, underlying FreeBSD gpart or ZFS utils should  purge disk more cleanly

**Comment by RodMyers** [comment]
run 

gpart show

also, have you tried the RELEASE ISO?

**Comment by RodMyers** [comment]
gpart show
=>       40  468862048  ada0  GPT  (224G)
         40     204800     1  efi  (100M)
     204840  466538496     2  freebsd-zfs  (222G)
  466743336    2097152     3  freebsd-swap  (1.0G)
  468840488      21600        - free -  (11M)

using the RELEASE ISO

**Comment by RodMyers** [comment]
I know have close access. forgot who I talked to earlier

thank you
