### ISSUE TITLE
Install location shows no disk until I go back and forth a few times

### ISSUE THREAD

**Issue by lsitongia** [project-trident/trident-installer#33]
Since I first tried Trident a month ago, and now with RC2, when I'm installing on my Intel NUC (model D34010WYK), I find that the Select Installation Location screen is empty. I found that I can go back to the Previous page, then go forward again it will populate the page with the disk and partitions. Sometimes it has taken four times back and forth to get the page populated.

**Comment by RodMyers** [comment]
please try the RELEASE ISO

**Comment by lsitongia** [comment]
I did a clean install using the release ISO and the install target disk was visible the first time. I proceeded with the install. I then rebooted the installer a couple of times. Every time, the target disk shows up the first time. Looks likes this is fixed. Thank you.

**Comment by RodMyers** [comment]
very good

closing ticket
