### ISSUE TITLE
Workaround for unclean drive during ZFS formatting

### ISSUE THREAD

**Issue by maxsteciuk** [project-trident/trident-installer#37]
Ideally I thought **gprart** would handle such case behind the scenes when acting on the *destroy* option.
But so that not to be dependent on upstream timelines would it be good idea to include the following step in the installer script  which does ZFS formatting?

> dd if=/dev/zero of=/dev/$DRIVE bs=$NBYTES

**Comment by RodMyers** [comment]
is this still an issue?

**Comment by beanpole135** [comment]
The TrueOS ISO cleaning options have already been updated to include a broader range of the disk that it zeroes out to prepare the disk for installation. This workaround should be not needed anymore.
