### ISSUE TITLE
Pre-Release of 11/23 Install Notes

### ISSUE THREAD

**Issue by jimbygh** [project-trident/trident-installer#38]
Install landing page:
* Go to terminal takes user off of GUI installer onto console vty (not sure if this is expected behavior)
* Text in ISO Date reads "ISO Data %1"
* Cannot expand System, Keyboard, and Local tabs.  They open fine, but I can't pull the grip farther to the right. (not sure if this is expected behavior)

Installation busy pages:
Layout of the images and text is still unpolished.

View Log
Cannot expand "View Log" panel (same behavior as above)

**Comment by beanpole135** [comment]
This has been fixed for quite a while now. Closing issue.
