### ISSUE TITLE
compiler-bootstrap not run after fresh installation : 18.12-PRERELEASE

### ISSUE THREAD

**Issue by ghost** [project-trident/trident-installer#40]
platform lenovo t530, 18.12-PRERELEASE 2018-12-07 fresh install

the llvm60-6.0.1_3 compiler is installed during a fresh installation but the compiler is not immediately usable until 

compiler-bootstrap llvm60   

is run to set up the missing links.  probably should add that to the overlay.

jpb

**Comment by jimbygh** [comment]
on a related note, i noticed that trueos (snapshot 208) is installing llvm70  by default, while trident (18.12-PRERELEASE) is installing llvm60 by default.

not sure if that is intended behavior or not...

**Comment by RodMyers** [comment]
as per telegram;

If you want to compile ports, then you need to install the OS-*-development packages.
