### ISSUE TITLE
virtualbox-ose  not installed from gui installer : 18.12-PRERELEASE

### ISSUE THREAD

**Issue by jimbygh** [project-trident/trident-installer#41]
platform lenovo t530, 18.12-PRERELEASE 2018.12.07

on an initial install, checking the "VirtualBox" application does not actually install the VirtualBox package.  it installs the "virtualbox-ose-additions"  package, which aren't really useful without the "virtualbox-ose"  package itself.

**Comment by jimbygh** [comment]
line 79 in packages.json

**Comment by beanpole135** [comment]
VirtualBox OSE is not included on the ISO - only the guest extensions.
That is why the "VirtualBox" line appears under the "Graphics Drivers" -> "Virtual Machine Guest" categories.
