### ISSUE TITLE
Issue with BE upgrade having multiple ZFS pools 

### ISSUE THREAD

**Issue by maxsteciuk** [project-trident/trident-installer#45]
Background:
The machine has had legacy TrueOS desktop 18.03 installed. Its ZFS pool is tank. It is located on a separate disk drive.  Trident installation also resides on its own separate drive where its ZFS pool is trident. 

Scenario:
1. Selecting BE upgrade for an existing Trident installation by checking radio button “Boot Environment”  at “Select Installation Location” step and selecting trident by hovering mouse over it so the option is highlighted 
2. At “System Installation Summary” step configuration shows:
installMode=upgrade
zpoolName=tank # <———- expected trident, this TrueOS 18.03 pool where this BE install would not be compatible 
3. Going back to “Select Installation Location” and selecting the opposite option “tank” 
4. Again proceeding to “System Installation Summary” step where configuration is:
installMode=fresh # <———— expected upgrade , which would fail anyway because disk drive info was not provided
zpoolName=trident

Problem:
The configuration summary is read-only in UI and at this step it still seems to be in the installer process memory so it’s not possible to correct / override it

Solution:
1. Fix  update of installMode and zpoolName from UI 
OR
2. Enable changing / overriding the resulting  “System Installation Summary” configuration

**Comment by maxsteciuk** [comment]
On 18.12-RELEASE-U8 this seems to be resolved as I was successfully able to select BE upgrade option, target zpool and the resulting script options were correctly generated accordingly

**Comment by RodMyers** [comment]
closing with the comment from April 6
