### ISSUE TITLE
Target drive selection error

### ISSUE THREAD

**Issue by ZoltanHegedus** [project-trident/trident-installer#50]
If I write the new Trident-x64-TOS-19.07-20190710 installer .iso for an DVD than the installer can't find  my HDD and my SSD, when I have to choose the target drives (after the time zone and hostname) or the target partitions of the new system the list is empty. This error already was earlier and solved.
 Now if I open a terminal (from the installer) to  partitioning and I'm exiting from this terminal than the  "Installation is ready - Reboot or Live CD"  blue screen come up again.

If I write the installer .iso for an USB key with dd command (block size 1M) than I can choose the target drives and I can make a fresh install, but in the newly installed system all the keyboard layout are empty,I can use my keyboard only with the default US layout.

Interesting the two different behavior of the intaller .iso (in the case of DVD or USB key) maybe the block size can cause this, I will try to write with different block sizes.

**Comment by ZoltanHegedus** [comment]
At the new Trident-x64-TOS-12-U2-20190808.iso if I start the installer from USB key (.iso) in legacy BIOS mode and in UEFI BIOS mode than the available drives are visible and they are optional for first.

If I start the installer from DVD (.iso)  in legacy BIOS mode and in UEFI BIOS mode than the target drive selection field (second step in the graphical installer) is empty for first. If I shift between the first step and the second step few times,  just than the drives will be visible and optional.

**Comment by beanpole135** [comment]
Closing issue.
 With the switch to Void Linux going forward, these issues with device detection are changing or vanishing completely with the new installer backend.
