### ISSUE TITLE
start-trident-installer doesn't handle wifi names with space in it

### ISSUE THREAD

**Issue by Johnnynator** [project-trident/trident-installer#66]
https://github.com/project-trident/trident-installer/blob/2ffb0836e679a924bc311c6d0de3cc40eeb8bd3f/src-sh/iso-overlay/usr/local/bin/start-trident-installer#L96
You just get the last part of the SSID, so `My Network SSID` does get shown as `SSID`.

**Comment by beanpole135** [comment]
Good catch!
Any idea on fixing this? The problem is that the delimiter for that output is whitespace, but If there are multiple line entries with whitespace in them, the parsing gets all funky. Perhaps use the BSSID as the network ID instead?

**Comment by Johnnynator** [comment]
I don't know how stable the format is and if the SSID always starts at after the 5th whitespace. If it does you could just go `echo $_line | cut -d ' ' -f 5-`

**Comment by beanpole135** [comment]
Committed!
We will have to test this out a bit more to make sure the parsing is reliable long-term, but it is better than what was there initially. Thanks!
